// Code generated by opticsgen; DO NOT EDIT.

package main

import (
	"context"

	"github.com/ichiban/optics"
)

// userName is a lens focusing on the name field of user.
var userName = optics.Lens[user, string]{
	View: func(_ context.Context, s user) (string, error) {
		return s.name, nil
	},
	Update: func(_ context.Context, s user, v string) (user, error) {
		s.name = v
		return s, nil
	},
}

// userAge is a lens focusing on the age field of user.
var userAge = optics.Lens[user, *int]{
	View: func(_ context.Context, s user) (*int, error) {
		return s.age, nil
	},
	Update: func(_ context.Context, s user, v *int) (user, error) {
		s.age = v
		return s, nil
	},
}
